packages:
  - "apps/sdkwork-course-h5"
  - "apps/sdkwork-course-h5/packages/*"
  - "apps/sdkwork-course-mini-program"
  - "apps/sdkwork-course-mini-program/packages/*"
  - "apps/sdkwork-course-pc"
  - "apps/sdkwork-course-pc/packages/*"
  - "sdks/_shared/*"
  - "sdks/*"
  - "sdks/sdkwork-course-app-sdk/sdkwork-course-app-sdk-typescript/generated/server-openapi"
  - "sdks/sdkwork-course-backend-sdk/sdkwork-course-backend-sdk-typescript/generated/server-openapi"
  - "apps/*"
  - "apps/sdkwork-course-mini-program/packages/*"

catalog:
  typescript: ~6.0.2
