use sdkwork_web_contract::HttpMethod;
use sdkwork_web_core::{HttpRoute, HttpRouteManifest};

const HTTP_ROUTES: &[HttpRoute] = &[
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/course_categories",
        "course",
        "courseCategories.list",
    ).with_required_permission("course.categories.read"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/course_categories/{categoryId}",
        "course",
        "courseCategories.retrieve",
    ).with_required_permission("course.categories.read"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/courses",
        "course",
        "courses.list",
    ).with_required_permission("course.courses.read"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/courses/{courseId}",
        "course",
        "courses.retrieve",
    ).with_required_permission("course.courses.read"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/courses/{courseId}/offerings",
        "course",
        "courseOfferings.list",
    ).with_required_permission("course.offerings.read"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/course_offerings/{offeringId}",
        "course",
        "courseOfferings.retrieve",
    ).with_required_permission("course.offerings.read"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/course_offerings/{offeringId}/enrollments",
        "course",
        "courseEnrollments.create",
    ).with_required_permission("course.enrollments.write"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/course_enrollments",
        "course",
        "courseEnrollments.current.list",
    ).with_required_permission("course.enrollments.read"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/course_enrollments/{enrollmentId}",
        "course",
        "courseEnrollments.retrieve",
    ).with_required_permission("course.enrollments.read"),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/app/v3/api/course_enrollments/{enrollmentId}",
        "course",
        "courseEnrollments.delete",
    ).with_required_permission("course.enrollments.write"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/courses/{courseId}/sections",
        "course",
        "courseSections.list",
    ).with_required_permission("course.lessons.read"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/courses/{courseId}/lessons",
        "course",
        "courseLessons.list",
    ).with_required_permission("course.lessons.read"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/course_lessons/{lessonId}",
        "course",
        "courseLessons.retrieve",
    ).with_required_permission("course.lessons.read"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/course_lessons/{lessonId}/resources",
        "course",
        "courseLessonResources.list",
    ).with_required_permission("course.resources.read"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/course_enrollments/{enrollmentId}/progress",
        "course",
        "courseProgress.retrieve",
    ).with_required_permission("course.progress.read"),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/app/v3/api/course_lessons/{lessonId}/progress",
        "course",
        "courseLessonProgress.update",
    ).with_required_permission("course.progress.write"),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/app/v3/api/course_lessons/{lessonId}/watch_position",
        "course",
        "courseLessonProgress.watchPositions.update",
    ).with_required_permission("course.progress.write"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/course_live_sessions",
        "course",
        "courseLiveSessions.list",
    ).with_required_permission("course.live_sessions.read"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/course_live_sessions/{liveSessionId}",
        "course",
        "courseLiveSessions.retrieve",
    ).with_required_permission("course.live_sessions.read"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/course_live_sessions/{liveSessionId}/join",
        "course",
        "courseLiveSessions.join",
    ).with_required_permission("course.live_sessions.join"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/course_live_sessions/{liveSessionId}/heartbeat",
        "course",
        "courseLiveSessions.heartbeat",
    ).with_required_permission("course.live_sessions.join"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/course_live_sessions/{liveSessionId}/leave",
        "course",
        "courseLiveSessions.leave",
    ).with_required_permission("course.live_sessions.join"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/course_live_sessions/{liveSessionId}/replay",
        "course",
        "courseLiveSessions.replay.retrieve",
    ).with_required_permission("course.live_sessions.read"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/courses/{courseId}/comments",
        "course",
        "courseComments.list",
    ).with_required_permission("course.comments.read"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/courses/{courseId}/comments",
        "course",
        "courseComments.create",
    ).with_required_permission("course.comments.write"),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/app/v3/api/course_comments/{commentId}",
        "course",
        "courseComments.delete",
    ).with_required_permission("course.comments.write"),
    HttpRoute::dual_token(
        HttpMethod::Put,
        "/app/v3/api/course_reactions",
        "course",
        "courseReactions.update",
    ).with_required_permission("course.reactions.write"),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/app/v3/api/course_reactions/{reactionId}",
        "course",
        "courseReactions.delete",
    ).with_required_permission("course.reactions.write"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/course_applications",
        "course",
        "courseApplications.create",
    ).with_required_permission("course.applications.write"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/course_applications",
        "course",
        "courseApplications.current.list",
    ).with_required_permission("course.applications.read"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/course_applications/{applicationId}",
        "course",
        "courseApplications.retrieve",
    ).with_required_permission("course.applications.read"),
];

pub fn course_app_api_http_route_manifest() -> HttpRouteManifest {
    HttpRouteManifest::new(HTTP_ROUTES)
}
