[package]
name = "sdkwork-api-course-assembly"
edition.workspace = true
license.workspace = true
version.workspace = true
description = "Generated API assembly for sdkwork-course application HTTP plane."

[lib]
name = "sdkwork_api_course_assembly"
path = "src/lib.rs"

[dependencies]
axum.workspace = true
tokio.workspace = true
sdkwork-web-bootstrap.workspace = true
sdkwork-course-embedded-bootstrap = { path = "../sdkwork-course-embedded-bootstrap" }
sdkwork_routes_course_http_auth = { package = "sdkwork-routes-course-http-auth", path = "../sdkwork-routes-course-http-auth" }
sdkwork-routes-course-app-api = { path = "../sdkwork-routes-course-app-api" }
sdkwork-routes-course-backend-api = { path = "../sdkwork-routes-course-backend-api" }
